ecgpb.member.index.index:
    pattern: /
    defaults: { _controller: "EcgpbMemberBundle:Index:index", _locale: de }

# person actions

ecgpb.member.person.index:
    pattern:  /person/index
    defaults: { _controller: "EcgpbMemberBundle:Person:index", _locale: de }

ecgpb.member.person.new:
    pattern:  /person/new
    defaults: { _controller: "EcgpbMemberBundle:Person:new", _locale: de }

ecgpb.member.person.create:
    pattern:  /person/create
    defaults: { _controller: "EcgpbMemberBundle:Person:create", _locale: de }
    requirements: { _method: post }

ecgpb.member.person.edit:
    pattern:  /person/{id}/edit
    defaults: { _controller: "EcgpbMemberBundle:Person:edit", _locale: de }

ecgpb.member.person.update:
    pattern:  /person/{id}/update
    defaults: { _controller: "EcgpbMemberBundle:Person:update", _locale: de }
    requirements: { _method: post|put }

ecgpb.member.person.delete:
    pattern:  /person/{id}/delete
    defaults: { _controller: "EcgpbMemberBundle:Person:delete", _locale: de }

# address routes

ecgpb.member.address.index:
    pattern:  /address/index
    defaults: { _controller: "EcgpbMemberBundle:Address:index", _locale: de }

ecgpb.member.address.new:
    pattern:  /address/new
    defaults: { _controller: "EcgpbMemberBundle:Address:new", _locale: de }

ecgpb.member.address.create:
    pattern:  /address/create
    defaults: { _controller: "EcgpbMemberBundle:Address:create", _locale: de }
    requirements: { _method: post }

ecgpb.member.address.edit:
    pattern:  /address/{id}/edit
    defaults: { _controller: "EcgpbMemberBundle:Address:edit", _locale: de }

ecgpb.member.address.update:
    pattern:  /address/{id}/update
    defaults: { _controller: "EcgpbMemberBundle:Address:update", _locale: de }
    requirements: { _method: post|put }

ecgpb.member.address.delete:
    pattern:  /address/{id}/delete
    defaults: { _controller: "EcgpbMemberBundle:Address:delete", _locale: de }

# print actions

ecgpb.member.print.html:
    pattern:  /print/html
    defaults: { _controller: "EcgpbMemberBundle:Print:html", _locale: de }

ecgpb.member.print.pdf:
    pattern:  /print/pdf
    defaults: { _controller: "EcgpbMemberBundle:Print:pdf", _locale: de }
    