ecgpb.member.index.index:
    pattern: /
    defaults: { _controller: "EcgpbMemberBundle:Index:index", _locale: de }

ecgpb.member.index.encode_password:
    pattern: /index/encode_password
    defaults: { _controller: "EcgpbMemberBundle:Index:encodePassword", _locale: de }

# person actions

ecgpb.member.person.index:
    pattern:  /person/index
    defaults: { _controller: "EcgpbMemberBundle:Person:index", _locale: de }

ecgpb.member.person.new:
    pattern:  /person/new
    defaults: { _controller: "EcgpbMemberBundle:Person:new", _locale: de }

ecgpb.member.person.create:
    pattern:  /person/create
    defaults: { _controller: "EcgpbMemberBundle:Person:create", _locale: de }
    requirements: { _method: post }

ecgpb.member.person.edit:
    pattern:  /person/{id}/edit
    defaults: { _controller: "EcgpbMemberBundle:Person:edit", _locale: de }

ecgpb.member.person.update:
    pattern:  /person/{id}/update
    defaults: { _controller: "EcgpbMemberBundle:Person:update", _locale: de }
    requirements: { _method: post|put }

ecgpb.member.person.delete:
    pattern:  /person/{id}/delete
    defaults: { _controller: "EcgpbMemberBundle:Person:delete", _locale: de }

ecgpb.member.person.optimized_member_picture:
    pattern:  /person/optimized_member_picture/{id}
    defaults: { _controller: "EcgpbMemberBundle:Person:optimizedMemberPicture", _locale: de }


# address routes

ecgpb.member.address.index:
    pattern:  /address/index
    defaults: { _controller: "EcgpbMemberBundle:Address:index", _locale: de }

ecgpb.member.address.new:
    pattern:  /address/new
    defaults: { _controller: "EcgpbMemberBundle:Address:new", _locale: de }

ecgpb.member.address.create:
    pattern:  /address/create
    defaults: { _controller: "EcgpbMemberBundle:Address:create", _locale: de }
    requirements: { _method: post }

ecgpb.member.address.edit:
    pattern:  /address/{id}/edit
    defaults: { _controller: "EcgpbMemberBundle:Address:edit", _locale: de }

ecgpb.member.address.update:
    pattern:  /address/{id}/update
    defaults: { _controller: "EcgpbMemberBundle:Address:update", _locale: de }
    requirements: { _method: post|put }

ecgpb.member.address.delete:
    pattern:  /address/{id}/delete
    defaults: { _controller: "EcgpbMemberBundle:Address:delete", _locale: de }

# working group actions

ecgpb.member.workinggroup.index:
    pattern:  /workinggroup/
    defaults: { _controller: "EcgpbMemberBundle:WorkingGroup:index" }

ecgpb.member.workinggroup.new:
    pattern:  /workinggroup/new
    defaults: { _controller: "EcgpbMemberBundle:WorkingGroup:new" }

ecgpb.member.workinggroup.create:
    pattern:  /workinggroup/create
    defaults: { _controller: "EcgpbMemberBundle:WorkingGroup:create" }
    requirements: { _method: post }

ecgpb.member.workinggroup.edit:
    pattern:  /workinggroup/{id}/edit
    defaults: { _controller: "EcgpbMemberBundle:WorkingGroup:edit" }

ecgpb.member.workinggroup.update:
    pattern:  /workinggroup/{id}/update
    defaults: { _controller: "EcgpbMemberBundle:WorkingGroup:update" }
    requirements: { _method: post|put }

ecgpb.member.workinggroup.delete:
    pattern:  /workinggroup/{id}/delete
    defaults: { _controller: "EcgpbMemberBundle:WorkingGroup:delete" }

# ministry category actions

ecgpb.member.ministry_category.index:
    pattern:  /ministry_category/
    methods: [GET]
    defaults: { _controller: "EcgpbMemberBundle:MinistryCategory:index" }

ecgpb.member.ministry_category.update:
    pattern:  /ministry_category/
    methods: [POST, PUT]
    defaults: { _controller: "EcgpbMemberBundle:MinistryCategory:update" }
    requirements:
        _format: json

# ministry groups actions

ecgpb.member.ministry_group.index:
    pattern:  /ministry_group/
    methods: [GET]
    defaults: { _controller: "EcgpbMemberBundle:MinistryGroup:index" }

ecgpb.member.ministry_group.update:
    pattern:  /ministry_group/
    methods: [POST, PUT]
    defaults: { _controller: "EcgpbMemberBundle:MinistryGroup:update" }
    requirements:
        _format: json

# export actions

ecgpb.member.export.pdf_config:
    pattern:  /export/pdf_config
    defaults: { _controller: "EcgpbMemberBundle:Export:pdfConfig", _locale: de }

ecgpb.member.export.pdf:
    pattern:  /export/pdf
    defaults: { _controller: "EcgpbMemberBundle:Export:pdf", _locale: de }

ecgpb.member.export.birthday_excel:
    pattern:  /export/birthday_excel
    defaults: { _controller: "EcgpbMemberBundle:Export:birthdayExcel", _locale: de }

ecgpb.member.export.seniors_excel:
    pattern:  /export/seniors_excel
    defaults: { _controller: "EcgpbMemberBundle:Export:seniorsExcel", _locale: de }
    