parameters:
#    ecgpb_member.example.class: Ecgpb\MemberBundle\Example

services:
#    ecgpb_member.example:
#        class: %ecgpb_member.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
