parameters:
#    ecgpb_member.example.class: Ecgpb\MemberBundle\Example

services:
#    ecgpb.member.event.entity_removal_subscriber:
#        class: Ecgpb\MemberBundle\Event\EntityRemovalSubscriber
#        arguments:
#            - "@doctrine"
#        tags:
#            - { name: doctrine.event_subscriber, connection: default }
