imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en

framework:
    #esi:             ~
    translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # http://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id:  session.handler.native_file
        save_path:   "%kernel.root_dir%/../var/sessions/%kernel.environment%"
    fragments:       ~
    http_method_override: true
    assets: ~
    php_errors:
        log: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    #form:
    #    resources:
    #        - ":Form:fields.html.twig"
    globals:
        ecgpb_contact_name_html:                %ecgpb.contact.name_html%
        ecgpb_contact_street:                   %ecgpb.contact.street%
        ecgpb_contact_zip:                      %ecgpb.contact.zip%
        ecgpb_contact_city:                     %ecgpb.contact.city%
        ecgpb_contact_main_phone:               %ecgpb.contact.main_phone%
        ecgpb_contact_office_phone_label:       %ecgpb.contact.office_phone_label%
        ecgpb_contact_office_phone:             %ecgpb.contact.office_phone%
        ecgpb_contact_kitchen_phone:            %ecgpb.contact.kitchen_phone%
        ecgpb_contact_library_phone:            %ecgpb.contact.library_phone%
        ecgpb_contact_library_email:            %ecgpb.contact.library_email%
        ecgpb_contact_bank_iban:                %ecgpb.contact.bank.iban%
        ecgpb_contact_bank_bic:                 %ecgpb.contact.bank.bic%
        ecgpb_contact_memberlist_responsible:   %ecgpb.contact.memberlist.responsible%
        ecgpb_contact_memberlist_email:         %ecgpb.contact.memberlist.email%

# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_sqlite
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/../var/data/data.sqlite"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

mopa_bootstrap:
    form:
        show_legend: false       # default is true
        show_child_legend: false # default is true
        error_type: block        # or inline which is default
        horizontal_label_class: "col-md-3"
        horizontal_input_wrapper_class: "col-md-offset-3"
        collection:
            widget_remove_btn:
                attr:
                    class:                "btn btn-danger"
                wrapper_div:
                    class:                col-md-3
                label:                false
                icon:                 remove
                icon_inverted:        false
    #menu: ~  # enables twig helpers for menu

knp_paginator:
    template:
        pagination: KnpPaginatorBundle:Pagination:twitter_bootstrap_v3_pagination.html.twig
