ecgpb:
    pattern: /
    defaults: { _controller: "EcgpbMemberBundle:Index:index", _locale: de }

ecgpb.member:
    resource: "@EcgpbMemberBundle/Resources/config/routing.yml"
    prefix:   /{_locale}

