security:
    encoders:
        Symfony\Component\Security\Core\User\User:
            algorithm:           sha1
            encode_as_base64:    true
            iterations:          1000

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        in_memory:
            memory:
                users:
                    admin:
                        password: %ecgpb.security.user.admin.password%
                        roles: [ 'ROLE_SUPER_ADMIN' ]

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login:
            pattern:  ^/$
            security: false

        secured_area:
            pattern:    ^/
            anonymous: ~
#            http_basic:
#                realm: "Secured Demo Area"

    access_control:
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
