Ecgpb\MemberBundle\Entity\Ministry:
    properties:
        name:
            serialized_name: name
            groups: [MinistryCategoryListing]
#        ministries:
#            groups: [MinistryCategoryListing]