Ecgpb\MemberBundle\Entity\Ministry\Group:
    properties:
        id:
            serialized_name: id
            groups: [MinistryCategoryListing]
        name:
            groups: [MinistryCategoryListing]