Ecgpb\MemberBundle\Entity\Ministry\ContactAssignment:
    properties:
        id:
            serialized_name: id
            groups: [MinistryCategoryListing]
        person:
            groups: [MinistryCategoryListing]
        group:
            groups: [MinistryCategoryListing]