Ecgpb\MemberBundle\Entity\Ministry\Category:
    properties:
        name:
            serialized_name: name
            groups: [MinistryCategoryListing]
        ministries:
            groups: [MinistryCategoryListing]