Ecgpb\MemberBundle\Entity\Ministry:
    properties:
        name:
            serialized_name: name
            groups: [MinistryCategoryListing]
        description:
            groups: [MinistryCategoryListing]