Ecgpb\MemberBundle\Entity\Person:
    properties:
        id:
            serialized_name: id
            groups: [MinistryCategoryListing]
        firstname:
            groups: [MinistryCategoryListing]
        address:
            groups: [MinistryCategoryListing]