Ecgpb\MemberBundle\Entity\Address:
    properties:
        id:
            serialized_name: id
            groups: [MinistryCategoryListing]
        familyName:
            serialized_name: familyName
            groups: [MinistryCategoryListing]