ecgpb.member.index.encode_password:
    path: /index/encode_password
    defaults: { _controller: "AppBundle:Index:encodePassword", _locale: de }

# person actions

ecgpb.member.person.index:
    path:  /person/index
    defaults: { _controller: "AppBundle:Person:index", _locale: de }

ecgpb.member.person.new:
    path:  /person/new
    defaults: { _controller: "AppBundle:Person:new", _locale: de }

ecgpb.member.person.create:
    path:  /person/create
    defaults: { _controller: "AppBundle:Person:create", _locale: de }
    requirements: { _method: post }

ecgpb.member.person.edit:
    path:  /person/{id}/edit
    defaults: { _controller: "AppBundle:Person:edit", _locale: de }

ecgpb.member.person.update:
    path:  /person/{id}/update
    defaults: { _controller: "AppBundle:Person:update", _locale: de }
    requirements: { _method: post|put }

ecgpb.member.person.delete:
    path:  /person/{id}/delete
    defaults: { _controller: "AppBundle:Person:delete", _locale: de }

ecgpb.member.person.optimized_member_picture:
    path:  /person/optimized_member_picture/{id}
    defaults: { _controller: "AppBundle:Person:optimizedMemberPicture", _locale: de }


# address routes

ecgpb.member.address:
    resource: "@AppBundle/Controller/AddressController.php"
    type: annotation
    prefix: /address

# working group actions

ecgpb.member.workinggroup:
    resource: "@AppBundle/Controller/WorkingGroupController.php"
    type: annotation
    prefix: /workinggroup

# ministry category actions

ecgpb.member.ministry_category.index:
    path:  /ministry_category/
    methods: [GET]
    defaults: { _controller: "AppBundle:MinistryCategory:index" }

ecgpb.member.ministry_category.update:
    path:  /ministry_category/
    methods: [POST, PUT]
    defaults: { _controller: "AppBundle:MinistryCategory:update" }
    requirements:
        _format: json

# ministry groups actions

ecgpb.member.ministry_group.index:
    path:  /ministry_group/
    methods: [GET]
    defaults: { _controller: "AppBundle:MinistryGroup:index" }

ecgpb.member.ministry_group.update:
    path:  /ministry_group/
    methods: [POST, PUT]
    defaults: { _controller: "AppBundle:MinistryGroup:update" }
    requirements:
        _format: json

# export actions

ecgpb.member.export:
    resource: "@AppBundle/Controller/ExportController.php"
    type: annotation
    prefix: /export
    defaults: { _locale: de }
