ecgpb.member.index.encode_password:
    path: /index/encode_password
    defaults: { _controller: "AppBundle:Index:encodePassword", _locale: de }

# address routes

ecgpb.member.address:
    resource: "@AppBundle/Controller/AddressController.php"
    type: annotation
    prefix: /address

# working group actions

ecgpb.member.workinggroup:
    resource: "@AppBundle/Controller/WorkingGroupController.php"
    type: annotation
    prefix: /workinggroup

# ministry category actions

ecgpb.member.ministry_category.index:
    path:  /ministry_category/
    methods: [GET]
    defaults: { _controller: "AppBundle:MinistryCategory:index" }

ecgpb.member.ministry_category.update:
    path:  /ministry_category/
    methods: [POST, PUT]
    defaults: { _controller: "AppBundle:MinistryCategory:update" }
    requirements:
        _format: json

# ministry groups actions

ecgpb.member.ministry_group.index:
    path:  /ministry_group/
    methods: [GET]
    defaults: { _controller: "AppBundle:MinistryGroup:index" }

ecgpb.member.ministry_group.update:
    path:  /ministry_group/
    methods: [POST, PUT]
    defaults: { _controller: "AppBundle:MinistryGroup:update" }
    requirements:
        _format: json

# export actions

ecgpb.member.export:
    resource: "@AppBundle/Controller/ExportController.php"
    type: annotation
    prefix: /export
    defaults: { _locale: de }
