Ecgpb\MemberBundle\Entity\Ministry\Category:
    properties:
        id:
            serialized_name: id
            groups: [MinistryCategoryListing]
        name:
            groups: [MinistryCategoryListing]
        position:
            groups: [MinistryCategoryListing]
        responsible:
            groups: [MinistryCategoryListing]
        ministries:
            groups: [MinistryCategoryListing]