Ecgpb\MemberBundle\Entity\Ministry\Group:
    properties:
        id:
            serialized_name: id
            groups: [MinistryCategoryListing, MinistryGroupListing]
        name:
            groups: [MinistryCategoryListing, MinistryGroupListing]
        persons:
            groups: [MinistryGroupListing]