AppBundle\Entity\Ministry:
    properties:
        id:
            serialized_name: id
            groups: [MinistryCategoryListing]
        name:
            groups: [MinistryCategoryListing]
        description:
            groups: [MinistryCategoryListing]
        position:
            groups: [MinistryCategoryListing]
        responsibleAssignments:
            serialized_name: responsibleAssignments
            groups: [MinistryCategoryListing]