Ecgpb\MemberBundle\Entity\Person:
    properties:
        id:
            serialized_name: id
            groups: [MinistryCategoryListing, MinistryGroupListing]
        firstname:
            groups: [MinistryCategoryListing, MinistryGroupListing]
        address:
            groups: [MinistryCategoryListing, MinistryGroupListing]
        dob:
            groups: [MinistryCategoryListing, MinistryGroupListing]