Ecgpb\MemberBundle\Entity\Ministry\Category:
    type: entity
    table: ministry_category
    repositoryClass: Ecgpb\MemberBundle\Repository\Ministry\CategoryRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: '40'
    oneToMany:
        ministries:
            targetEntity: Ecgpb\MemberBundle\Entity\Ministry
            cascade: [persist]
            mappedBy: category
    lifecycleCallbacks: {  }
