AppBundle\Entity\Address:
    type: entity
    repositoryClass: AppBundle\Repository\AddressRepository
    table: address
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        familyName:
            column: familyName
            type: string
            length: '50'
        phone:
            type: string
            length: '30'
            nullable: true
        street:
            type: string
            length: '50'
            nullable: true
        zip:
            type: string
            length: '5'
            nullable: true
        city:
            type: string
            length: '40'
            nullable: true
    oneToMany:
        persons:
            targetEntity: AppBundle\Entity\Person
            cascade: [ persist, remove ]
            mappedBy: address
            orphanRemoval: true
    lifecycleCallbacks: {  }
