Ecgpb\MemberBundle\Entity\Address:
    type: entity
    repositoryClass: Ecgpb\MemberBundle\Repository\AddressRepository
    table: address
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        familyName:
            type: string
            length: '50'
        phone:
            type: string
            length: '30'
            nullable: true
        street:
            type: string
            length: '50'
            nullable: true
        zip:
            type: string
            length: '5'
            nullable: true
        city:
            type: string
            length: '40'
            nullable: true
    oneToMany:
        persons:
            targetEntity: Ecgpb\MemberBundle\Entity\Person
            cascade: [ persist, remove ]
            mappedBy: address
    lifecycleCallbacks: {  }
