AppBundle\Entity\Ministry\ResponsibleAssignment:
    type: entity
    table: ministry_assignment_responsible
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields: ~
    manyToOne:
        ministry:
            targetEntity: AppBundle\Entity\Ministry
            inversedBy: responsibleAssignments
            joinColumn:
                name: ministry_id
                nullable: false
                onDelete: CASCADE
        person:
            targetEntity: AppBundle\Entity\Person
            inversedBy: ministryResponsibleAssignments
            joinColumn:
                name: person_id
                nullable: true
                onDelete: CASCADE
        group:
            targetEntity: AppBundle\Entity\Ministry\Group
            joinColumn:
                name: group_id
                nullable: true
                onDelete: CASCADE
    lifecycleCallbacks: {  }
