AppBundle\Entity\Person:
    type: entity
    table: person
    repositoryClass: AppBundle\Repository\PersonRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        lastname:
            type: string
            length: 30
            nullable: true
            comment: 'Last name can be empty. In that case the last name is taken from address entity (family name)'
        firstname:
            type: string
            length: 30
        dob:
            type: date
        gender:
            type: string
            length: '1'
        mobile:
            type: string
            length: '30'
            nullable: true
        email:
            type: string
            length: '100'
            nullable: true
        phone2:
            type: string
            length: '30'
            nullable: true
        phone2Label:
            column: phone2Label
            type: string
            length: 40
            nullable: true
        maidenName:
            column: maidenName
            type: string
            length: '40'
            nullable: true
        workerStatus:
            column: workerStatus
            type: smallint
            nullable: false
    oneToOne:
        leaderOf:
            targetEntity: AppBundle\Entity\WorkingGroup
            mappedBy: leader
    oneToMany:
        ministryResponsibleAssignments:
            targetEntity: AppBundle\Entity\Ministry\ResponsibleAssignment
            cascade: [ remove ]
            mappedBy: person
    manyToOne:
        address:
            targetEntity: AppBundle\Entity\Address
            inversedBy: persons
            cascade: [ persist ]
            joinColumn:
                name: address_id
                nullable: false
        workingGroup:
            targetEntity: AppBundle\Entity\WorkingGroup
            inversedBy: persons
            joinColumn:
                name: working_group_id
                nullable: true
                onDelete: 'SET NULL'
    lifecycleCallbacks: {  }
