AppBundle\Entity\WorkingGroup:
    type: entity
    table: working_group
    repositoryClass: AppBundle\Repository\WorkingGroupRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        number:
            type: integer
        gender:
            type: string
            length: 1
    oneToOne:
        leader:
            targetEntity: AppBundle\Entity\Person
            inversedBy: leaderOf
            joinColumn:
                name: leader_person_id
                nullable: true
    oneToMany:
        persons:
            targetEntity: AppBundle\Entity\Person
            mappedBy: workingGroup
    uniqueConstraints:
        uniqueGenderNumber:
            columns: [gender, number]
    lifecycleCallbacks: {  }
