:
    pattern:  /
    defaults: { _controller: "EcgpbMemberBundle:Person:index" }

_show:
    pattern:  /{id}/show
    defaults: { _controller: "EcgpbMemberBundle:Person:show" }

_new:
    pattern:  /new
    defaults: { _controller: "EcgpbMemberBundle:Person:new" }

_create:
    pattern:  /create
    defaults: { _controller: "EcgpbMemberBundle:Person:create" }
    requirements: { _method: post }

_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "EcgpbMemberBundle:Person:edit" }

_update:
    pattern:  /{id}/update
    defaults: { _controller: "EcgpbMemberBundle:Person:update" }
    requirements: { _method: post|put }

_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "EcgpbMemberBundle:Person:delete" }
    requirements: { _method: post|delete }
